  
  - name: Install containers and such
    hosts: all
    become: yes

    roles:
    - role: geerlingguy.docker
      docker_compose_version: "v2.2.3"
      docker_users:
      - "{{ dest_user }}"
