
- name: Install nodejs
  hosts: all
  become: true
  
  tasks:
    - name: install nodejs
      apt:
        deb: https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.14.2-deb-1nodesource1_amd64.deb
